# --- Site ---
title: Julian Ockelmann
email: julian.ockelmann@gmail.com
author: Julian Ockelmann

# Profile links used on the home panels
scholar_url: "https://scholar.google.com/citations?user=HSduCL0AAAAJ&hl=en"
orcid_id: "0000-0002-4780-8993"
osf_url: "https://osf.io/92fa4/"
linkedin_url: "https://www.linkedin.com/in/julian-ockelmann-977208170/"

# Footer copyright (placeholders: {currentYear}, {author})
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"

description: "Ad Astra Per Aspera."
baseurl: ""         # e.g., /blog
url: ""             # e.g., https://example.com
favicon: ""         # /assets/images/favicon.png if you add one

# Theme (Yat) options
yat:
  date_format: "%b %d, %Y"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
